import { useState, MouseEvent } from 'react';
import NotificationsIcon from '@mui/icons-material/Notifications';
import NotificationsNoneIcon from '@mui/icons-material/NotificationsNone';
import PersonAddIcon from '@mui/icons-material/PersonAdd';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CancelIcon from '@mui/icons-material/Cancel';
import InfoIcon from '@mui/icons-material/Info';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import DeleteIcon from '@mui/icons-material/Delete';
import SecurityIcon from '@mui/icons-material/Security';
import ThumbUpIcon from '@mui/icons-material/ThumbUp';
import ThumbDownIcon from '@mui/icons-material/ThumbDown';
import { CircularProgress, Tooltip, IconButton, Button, Box } from '@mui/material';
import { useNotifications, useMarkNotificationRead, useMarkAllNotificationsRead, useDeleteNotification } from '../../api/entities/auth';
import { useRespondPermissionRequest } from '../../api/entities/auth/usePermissionRequests';
import type { NotificationDto } from '../../api/models/NotificationDto';
import type { SharePermissions } from '../../api/models/SharedAccountDto';
import { isSharedAccessSession } from '../../api/httpClient';
import { toastService } from '../../services';
import {
  BellButton,
  UnreadBadge,
  NotificationPopover,
  NotificationHeader,
  NotificationTitle,
  MarkAllButton,
  NotificationList,
  NotificationItem,
  NotificationIcon,
  NotificationContent,
  NotificationItemTitle,
  NotificationMessage,
  NotificationTime,
  EmptyNotifications,
  TempPasswordBox,
  NotificationActions,
} from './NotificationBell.styles';

function getRelativeTime(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);

  if (diffMins < 1) return 'Just now';
  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

function getNotificationIcon(type: NotificationDto['type']) {
  switch (type) {
    case 'account_shared':
      return <PersonAddIcon fontSize="small" />;
    case 'share_accepted':
      return <CheckCircleIcon fontSize="small" />;
    case 'share_revoked':
      return <CancelIcon fontSize="small" />;
    case 'permission_request':
      return <SecurityIcon fontSize="small" />;
    case 'request_approved':
      return <ThumbUpIcon fontSize="small" />;
    case 'request_rejected':
      return <ThumbDownIcon fontSize="small" />;
    default:
      return <InfoIcon fontSize="small" />;
  }
}

// Permission name formatter
const PERMISSION_LABELS: Record<keyof SharePermissions, string> = {
  createDatabase: 'Create Database',
  connectDatabase: 'Connect Database',
  createTable: 'Create Table',
  addColumn: 'Add Column',
  editColumn: 'Edit Column',
  deleteColumn: 'Delete Column',
  deleteTable: 'Delete Table',
  viewTableData: 'View Table Data',
  editTableData: 'Edit Table Data',
  runQuery: 'Run Query',
  createApiInQueryBuilder: 'Create API in Query Builder',
  tryAutoGeneratedApis: 'Try Auto-Generated APIs',
  tryOpenApi: 'Try OpenAPI',
};

interface NotificationItemComponentProps {
  notification: NotificationDto;
  onRead: (id: number) => void;
  onDelete: (id: number) => void;
  onRespond?: (requestId: number, action: 'approve' | 'reject') => void;
  isResponding?: boolean;
}

function NotificationItemComponent({ notification, onRead, onDelete, onRespond, isResponding }: NotificationItemComponentProps) {
  const [copied, setCopied] = useState(false);
  const isRead = !!notification.readAt;
  const isShared = isSharedAccessSession();

  // Parse metadata to get temp password for account_shared notifications
  let tempPassword: string | null = null;
  let ownerEmail: string | null = null;
  let requestId: number | null = null;
  let permission: keyof SharePermissions | null = null;
  
  if (notification.metadata) {
    try {
      const metadata = notification.metadata as Record<string, unknown>;
      tempPassword = (metadata.tempPassword as string) || null;
      ownerEmail = (metadata.ownerEmail as string) || null;
      requestId = (metadata.requestId as number) || null;
      permission = (metadata.permission as keyof SharePermissions) || null;
    } catch {
      // Ignore parse errors
    }
  }

  // Permission request notifications show approve/reject buttons (only for owners, not shared users)
  const showPermissionActions = notification.type === 'permission_request' && requestId && !isShared;

  const handleClick = () => {
    if (!isRead) {
      onRead(notification.id);
    }
  };

  const handleCopyPassword = (e: MouseEvent) => {
    e.stopPropagation();
    if (tempPassword) {
      navigator.clipboard.writeText(tempPassword);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDelete = (e: MouseEvent) => {
    e.stopPropagation();
    onDelete(notification.id);
  };

  const handleApprove = (e: MouseEvent) => {
    e.stopPropagation();
    if (requestId && onRespond) {
      onRespond(requestId, 'approve');
    }
  };

  const handleReject = (e: MouseEvent) => {
    e.stopPropagation();
    if (requestId && onRespond) {
      onRespond(requestId, 'reject');
    }
  };

  return (
    <NotificationItem isRead={isRead} onClick={handleClick}>
      <NotificationIcon type={notification.type}>
        {getNotificationIcon(notification.type)}
      </NotificationIcon>
      <NotificationContent>
        <NotificationItemTitle>{notification.title}</NotificationItemTitle>
        <NotificationMessage>{notification.message}</NotificationMessage>
        {tempPassword && (
          <TempPasswordBox>
            <span className="password-label">Temporary Password</span>
            <div className="password-row">
              <code>{tempPassword}</code>
              <Tooltip title={copied ? 'Copied!' : 'Copy password'}>
                <IconButton size="small" onClick={handleCopyPassword}>
                  <ContentCopyIcon fontSize="small" />
                </IconButton>
              </Tooltip>
            </div>
          </TempPasswordBox>
        )}
        {showPermissionActions && (
          <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
            <Button
              size="small"
              variant="contained"
              color="success"
              startIcon={<ThumbUpIcon />}
              onClick={handleApprove}
              disabled={isResponding}
              sx={{ fontSize: '0.7rem', py: 0.25, px: 1 }}
            >
              Approve
            </Button>
            <Button
              size="small"
              variant="outlined"
              color="error"
              startIcon={<ThumbDownIcon />}
              onClick={handleReject}
              disabled={isResponding}
              sx={{ fontSize: '0.7rem', py: 0.25, px: 1 }}
            >
              Reject
            </Button>
          </Box>
        )}
        <NotificationTime>{getRelativeTime(notification.createdAt)}</NotificationTime>
      </NotificationContent>
      <NotificationActions>
        <Tooltip title="Delete notification">
          <IconButton size="small" onClick={handleDelete}>
            <DeleteIcon fontSize="small" />
          </IconButton>
        </Tooltip>
      </NotificationActions>
    </NotificationItem>
  );
}

export default function NotificationBell() {
  const [anchorEl, setAnchorEl] = useState<HTMLButtonElement | null>(null);
  const { data, isLoading, refetch } = useNotifications();
  const { markAsRead } = useMarkNotificationRead();
  const { markAllAsRead, isLoading: markingAll } = useMarkAllNotificationsRead();
  const { deleteNotification } = useDeleteNotification();
  const { respondPermissionRequest, isLoading: isResponding } = useRespondPermissionRequest({
    onSuccess: () => {
      toastService.success('Response recorded successfully');
      refetch(); // Refresh notifications after responding
    },
    onError: (err) => {
      toastService.error(err.body?.message || 'Failed to respond to request');
    },
  });

  const notifications = data?.data?.notifications || [];
  const unreadCount = data?.data?.unreadCount || 0;

  const handleOpen = (event: MouseEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  const handleMarkAllRead = () => {
    markAllAsRead();
  };

  const handleRespondToRequest = (requestId: number, action: 'approve' | 'reject') => {
    respondPermissionRequest({ requestId, action });
  };

  const open = Boolean(anchorEl);

  return (
    <>
      <BellButton onClick={handleOpen}>
        {unreadCount > 0 ? <NotificationsIcon /> : <NotificationsNoneIcon />}
        {unreadCount > 0 && (
          <UnreadBadge>{unreadCount > 99 ? '99+' : unreadCount}</UnreadBadge>
        )}
      </BellButton>

      <NotificationPopover
        open={open}
        anchorEl={anchorEl}
        onClose={handleClose}
        anchorOrigin={{
          vertical: 'bottom',
          horizontal: 'right',
        }}
        transformOrigin={{
          vertical: 'top',
          horizontal: 'right',
        }}
      >
        <NotificationHeader>
          <NotificationTitle>Notifications</NotificationTitle>
          {unreadCount > 0 && (
            <MarkAllButton onClick={handleMarkAllRead} disabled={markingAll}>
              {markingAll ? 'Marking...' : 'Mark all read'}
            </MarkAllButton>
          )}
        </NotificationHeader>

        <NotificationList>
          {isLoading ? (
            <EmptyNotifications>
              <CircularProgress size={24} />
            </EmptyNotifications>
          ) : notifications.length === 0 ? (
            <EmptyNotifications>
              <NotificationsNoneIcon />
              <span>No notifications yet</span>
            </EmptyNotifications>
          ) : (
            notifications.map((notification) => (
              <NotificationItemComponent
                key={notification.id}
                notification={notification}
                onRead={markAsRead}
                onDelete={deleteNotification}
                onRespond={handleRespondToRequest}
                isResponding={isResponding}
              />
            ))
          )}
        </NotificationList>
      </NotificationPopover>
    </>
  );
}
