import { useState } from 'react';
import { TextField, Tooltip, CircularProgress, Alert, Dialog, DialogTitle, DialogContent, DialogActions, FormControlLabel, Checkbox, Typography, Box, Accordion, AccordionSummary, AccordionDetails, IconButton, Collapse, Button, Chip, Skeleton } from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import PersonAddIcon from '@mui/icons-material/PersonAdd';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import EditIcon from '@mui/icons-material/Edit';
import SaveIcon from '@mui/icons-material/Save';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';
import CheckIcon from '@mui/icons-material/Check';
import CloseOutlinedIcon from '@mui/icons-material/CloseOutlined';
import { useShareAccount, useSharedAccounts, useRevokeShare, useDeleteShare, useUpdateSharePermissions, usePermissionRequests, useRespondPermissionRequest } from '../../../api/entities/auth';
import { toastService } from '../../../services';
import type { SharedAccountDto, SharePermissions, PermissionRequestDto } from '../../../api/models/SharedAccountDto';
import { DEFAULT_SHARE_PERMISSIONS } from '../../../api/models/SharedAccountDto';
import {
  ShareForm,
  ShareFormRow,
  ShareButton,
  ShareList,
  ShareCard,
  ShareInfo,
  ShareEmail,
  ShareMeta,
  StatusBadge,
  RevokeButton,
  TempPasswordLabel,
  TempPasswordValue,
  SectionDivider,
  SectionSubtitle,
  SectionHeader,
  ClearAllButton,
  EmptyState,
  SkeletonCard,
  SkeletonContainer,
} from './AccountSharing.styles';

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function getShareStatus(share: SharedAccountDto): 'pending' | 'accepted' | 'revoked' | 'expired' {
  if (share.status === 'revoked') return 'revoked';
  if (new Date(share.expiresAt) < new Date()) return 'expired';
  return share.status;
}

interface ShareAccountFormProps {
  onShareCreated: (share: SharedAccountDto, tempPassword: string) => void;
}

// Permission categories for organized display
const PERMISSION_CATEGORIES = {
  'Database Operations': ['createDatabase', 'connectDatabase'] as const,
  'Schema Operations': ['createTable', 'addColumn', 'editColumn', 'deleteColumn', 'deleteTable'] as const,
  'Data Operations': ['viewTableData', 'editTableData'] as const,
  'Query Operations': ['runQuery'] as const,
  'API Operations': ['createApiInQueryBuilder', 'tryAutoGeneratedApis', 'tryOpenApi'] as const,
};

const PERMISSION_LABELS: Record<keyof SharePermissions, string> = {
  createDatabase: 'Create Database',
  connectDatabase: 'Connect Database',
  createTable: 'Create Table',
  addColumn: 'Add Column',
  editColumn: 'Edit Column',
  deleteColumn: 'Delete Column',
  deleteTable: 'Delete Table',
  viewTableData: 'View Table Data',
  editTableData: 'Edit Table Data',
  runQuery: 'Run Query',
  createApiInQueryBuilder: 'Create API in Query Builder',
  tryAutoGeneratedApis: 'Try Auto-Generated APIs',
  tryOpenApi: 'Try OpenAPI',
};

function ShareAccountForm({ onShareCreated }: ShareAccountFormProps) {
  const [email, setEmail] = useState('');
  const [permissions, setPermissions] = useState<SharePermissions>({ ...DEFAULT_SHARE_PERMISSIONS });
  const [showPermissions, setShowPermissions] = useState(false);

  const { shareAccount, isLoading, error, reset } = useShareAccount({
    onSuccess: (data) => {
      const share = data.data.share;
      if (share.tempPassword) {
        onShareCreated(share, share.tempPassword);
      }
      toastService.success('Account shared successfully!');
      setEmail('');
      setPermissions({ ...DEFAULT_SHARE_PERMISSIONS });
      reset();
    },
    onError: (err) => {
      toastService.error(err.body?.message || 'Failed to share account');
    },
  });

  const handlePermissionChange = (permission: keyof SharePermissions) => {
    setPermissions(prev => ({
      ...prev,
      [permission]: !prev[permission],
    }));
  };

  const handleSelectAll = (category: keyof typeof PERMISSION_CATEGORIES) => {
    const categoryPermissions = PERMISSION_CATEGORIES[category];
    const allSelected = categoryPermissions.every(p => permissions[p]);
    setPermissions(prev => {
      const newPermissions = { ...prev };
      categoryPermissions.forEach(p => {
        newPermissions[p] = !allSelected;
      });
      return newPermissions;
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim()) return;
    shareAccount({ email: email.trim(), permissions });
  };

  return (
    <ShareForm onSubmit={handleSubmit}>
      {error && (
        <Alert severity="error" onClose={reset}>
          {error.body?.message || 'Failed to share account'}
        </Alert>
      )}
      <ShareFormRow>
        <TextField
          label="User Email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="Enter the email of the user to share with"
          size="small"
          fullWidth
          required
          sx={{ flex: 1 }}
        />
        <ShareButton type="submit" disabled={isLoading || !email.trim()}>
          {isLoading ? <CircularProgress size={20} color="inherit" /> : <PersonAddIcon sx={{ mr: 0.5 }} />}
          Share
        </ShareButton>
      </ShareFormRow>

      <Accordion
        expanded={showPermissions}
        onChange={() => setShowPermissions(!showPermissions)}
        sx={{ mt: 2, '&:before': { display: 'none' } }}
      >
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography variant="subtitle2">Access Permissions (Settings is always blocked)</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            {Object.entries(PERMISSION_CATEGORIES).map(([category, perms]) => (
              <Box key={category}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 1 }}>
                  <Typography variant="caption" color="textSecondary" sx={{ fontWeight: 600 }}>
                    {category}
                  </Typography>
                  <Typography
                    variant="caption"
                    color="primary"
                    sx={{ ml: 1, cursor: 'pointer', '&:hover': { textDecoration: 'underline' } }}
                    onClick={() => handleSelectAll(category as keyof typeof PERMISSION_CATEGORIES)}
                  >
                    {perms.every(p => permissions[p]) ? 'Deselect All' : 'Select All'}
                  </Typography>
                </Box>
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0 }}>
                  {perms.map((perm) => (
                    <FormControlLabel
                      key={perm}
                      control={
                        <Checkbox
                          size="small"
                          checked={permissions[perm]}
                          onChange={() => handlePermissionChange(perm)}
                        />
                      }
                      label={<Typography variant="body2">{PERMISSION_LABELS[perm]}</Typography>}
                      sx={{ minWidth: 200 }}
                    />
                  ))}
                </Box>
              </Box>
            ))}
          </Box>
        </AccordionDetails>
      </Accordion>
    </ShareForm>
  );
}

interface ShareCardItemProps {
  share: SharedAccountDto;
  isOwner: boolean;
  onRevoke?: (shareId: number) => void;
  onUpdatePermissions?: (shareId: number, permissions: SharePermissions) => Promise<void>;
  isRevoking?: boolean;
  isUpdating?: boolean;
  tempPassword?: string;
}

function ShareCardItem({ share, isOwner, onRevoke, onUpdatePermissions, isRevoking, isUpdating, tempPassword }: ShareCardItemProps) {
  const status = getShareStatus(share);
  const canRevoke = isOwner && (status === 'pending' || status === 'accepted');
  const canEditPermissions = isOwner && (status === 'pending' || status === 'accepted');

  const [expanded, setExpanded] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedPermissions, setEditedPermissions] = useState<SharePermissions>(share.permissions);

  const handleToggleExpand = () => {
    setExpanded(!expanded);
    if (!expanded) {
      // Reset edited permissions when expanding
      setEditedPermissions(share.permissions);
      setIsEditing(false);
    }
  };

  const handlePermissionChange = (permission: keyof SharePermissions) => {
    setEditedPermissions(prev => ({
      ...prev,
      [permission]: !prev[permission],
    }));
  };

  const handleSavePermissions = async () => {
    if (onUpdatePermissions) {
      await onUpdatePermissions(share.id, editedPermissions);
      setIsEditing(false);
    }
  };

  const handleCancelEdit = () => {
    setEditedPermissions(share.permissions);
    setIsEditing(false);
  };

  // Count enabled permissions
  const enabledCount = Object.values(share.permissions).filter(Boolean).length;
  const totalCount = Object.keys(share.permissions).length;

  return (
    <ShareCard style={{ flexDirection: 'column' }}>
      <div style={{ display: 'flex', alignItems: 'center', width: '100%' }}>
        <ShareInfo style={{ flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <ShareEmail>
              {isOwner ? share.sharedWithEmail : share.ownerEmail}
            </ShareEmail>
            <StatusBadge status={status}>{status}</StatusBadge>
          </div>
          <ShareMeta>
            {isOwner ? 'Shared with' : 'Shared by'}
            {isOwner && ` • ${enabledCount}/${totalCount} permissions`}
          </ShareMeta>
        </ShareInfo>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
          {isOwner && (status === 'pending' || status === 'accepted') && (
            <Tooltip title={expanded ? "Hide permissions" : "View/Edit permissions"}>
              <IconButton onClick={handleToggleExpand} size="small">
                {expanded ? <KeyboardArrowUpIcon /> : <KeyboardArrowDownIcon />}
              </IconButton>
            </Tooltip>
          )}
          {canRevoke && onRevoke && (
            <Tooltip title="Revoke access">
              <RevokeButton onClick={() => onRevoke(share.id)} disabled={isRevoking}>
                {isRevoking ? <CircularProgress size={16} /> : <CloseIcon />}
              </RevokeButton>
            </Tooltip>
          )}
        </div>
      </div>

      {/* Temp Password Display (inline in card) */}
      {tempPassword && (
        <Box sx={{
          mt: 2,
          pt: 2,
          borderTop: '1px solid',
          borderColor: 'divider',
          backgroundColor: 'rgba(76, 175, 80, 0.08)',
          borderRadius: 1,
          p: 1.5,
          mx: -1.5,
          mb: -1.5,
        }}>
          <Box sx={{ mb: 1 }}>
            <TempPasswordLabel sx={{ m: 0 }}>
              Temporary Password
            </TempPasswordLabel>
          </Box>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <TempPasswordValue>{tempPassword}</TempPasswordValue>
            <Tooltip title="Copy password">
              <ShareButton
                onClick={() => {
                  navigator.clipboard.writeText(tempPassword);
                  toastService.success('Password copied to clipboard');
                }}
                variant="outlined"
                size="small"
              >
                <ContentCopyIcon fontSize="small" />
              </ShareButton>
            </Tooltip>
          </Box>
          <ShareMeta sx={{ mt: 1 }}>
            Share this password with {share.sharedWithEmail}. They will use it to access your account.
          </ShareMeta>
        </Box>
      )}

      {/* Expandable Permissions Section */}
      {isOwner && (
        <Collapse in={expanded} timeout="auto" unmountOnExit>
          <Box sx={{
            mt: 2,
            pt: 2,
            borderTop: '1px solid',
            borderColor: 'divider',
          }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1.5 }}>
              <Typography variant="subtitle2" color="textSecondary">
                Access Permissions
              </Typography>
              {canEditPermissions && (
                <Box sx={{ display: 'flex', gap: 1 }}>
                  {isEditing ? (
                    <>
                      <Button
                        size="small"
                        variant="outlined"
                        onClick={handleCancelEdit}
                        disabled={isUpdating}
                      >
                        Cancel
                      </Button>
                      <Button
                        size="small"
                        variant="contained"
                        onClick={handleSavePermissions}
                        disabled={isUpdating}
                        startIcon={isUpdating ? <CircularProgress size={14} /> : <SaveIcon />}
                      >
                        Save
                      </Button>
                    </>
                  ) : (
                    <Button
                      size="small"
                      variant="outlined"
                      onClick={() => setIsEditing(true)}
                      startIcon={<EditIcon />}
                    >
                      Edit
                    </Button>
                  )}
                </Box>
              )}
            </Box>

            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
              {Object.entries(PERMISSION_CATEGORIES).map(([category, perms]) => (
                <Box key={category}>
                  <Typography variant="caption" color="textSecondary" sx={{ fontWeight: 600, fontSize: '0.7rem' }}>
                    {category}
                  </Typography>
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0, ml: -1 }}>
                    {perms.map((perm) => {
                      const currentPerms = isEditing ? editedPermissions : share.permissions;
                      return (
                        <FormControlLabel
                          key={perm}
                          control={
                            <Checkbox
                              size="small"
                              checked={currentPerms[perm]}
                              onChange={() => isEditing && handlePermissionChange(perm)}
                              disabled={!isEditing}
                              sx={{ padding: '4px' }}
                            />
                          }
                          label={
                            <Typography variant="body2" sx={{ fontSize: '0.8rem' }}>
                              {PERMISSION_LABELS[perm]}
                            </Typography>
                          }
                          sx={{ minWidth: 180, mr: 0 }}
                        />
                      );
                    })}
                  </Box>
                </Box>
              ))}
            </Box>
          </Box>
        </Collapse>
      )}
    </ShareCard>
  );
}

function formatTimeAgo(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return 'just now';
  if (diffMins < 60) return `${diffMins} min ago`;
  if (diffHours < 24) return `${diffHours} hour${diffHours > 1 ? 's' : ''} ago`;
  if (diffDays < 7) return `${diffDays} day${diffDays > 1 ? 's' : ''} ago`;
  return formatDate(dateString);
}

function PermissionRequestsPanel() {
  const { data: requestsData, isLoading } = usePermissionRequests();
  const { respondPermissionRequest, isLoading: responding } = useRespondPermissionRequest({
    onSuccess: () => {
      toastService.success('Response sent successfully');
    },
    onError: (err) => {
      toastService.error(err.body?.message || 'Failed to respond to request');
    },
  });

  const pendingRequests = requestsData?.data?.requests?.filter(r => r.status === 'pending') || [];

  if (isLoading) {
    return null;
  }

  if (pendingRequests.length === 0) {
    return null;
  }

  const handleApprove = (request: PermissionRequestDto) => {
    respondPermissionRequest({
      requestId: request.id,
      action: 'approve',
    });
  };

  const handleReject = (request: PermissionRequestDto) => {
    respondPermissionRequest({
      requestId: request.id,
      action: 'reject',
    });
  };

  return (
    <Box sx={{ mb: 3 }}>
      <Box sx={{
        display: 'flex',
        alignItems: 'center',
        gap: 1,
        mb: 1.5
      }}>
        <Typography variant="subtitle2" sx={{ fontWeight: 600 }}>
          Permission Requests
        </Typography>
        <Chip
          label={pendingRequests.length}
          size="small"
          color="warning"
          sx={{ height: 20, fontSize: '0.75rem' }}
        />
      </Box>
      <ShareList>
        {pendingRequests.map((request) => (
          <ShareCard key={request.id}>
            <ShareInfo>
              <ShareEmail>{request.requestedByEmail}</ShareEmail>
              <ShareMeta>
                Requesting: <strong>{PERMISSION_LABELS[request.permission] || request.permission}</strong>
              </ShareMeta>
              {request.message && (
                <ShareMeta sx={{ fontStyle: 'italic', mt: 0.5 }}>
                  "{request.message}"
                </ShareMeta>
              )}
              <ShareMeta sx={{ mt: 0.5 }}>{formatTimeAgo(request.createdAt)}</ShareMeta>
            </ShareInfo>
            <Box sx={{ display: 'flex', gap: 1 }}>
              <Tooltip title="Approve">
                <IconButton
                  size="small"
                  onClick={() => handleApprove(request)}
                  disabled={responding}
                  sx={{
                    color: 'success.main',
                    '&:hover': { backgroundColor: 'rgba(46, 125, 50, 0.1)' }
                  }}
                >
                  <CheckIcon fontSize="small" />
                </IconButton>
              </Tooltip>
              <Tooltip title="Reject">
                <IconButton
                  size="small"
                  onClick={() => handleReject(request)}
                  disabled={responding}
                  sx={{
                    color: 'error.main',
                    '&:hover': { backgroundColor: 'rgba(211, 47, 47, 0.1)' }
                  }}
                >
                  <CloseOutlinedIcon fontSize="small" />
                </IconButton>
              </Tooltip>
            </Box>
          </ShareCard>
        ))}
      </ShareList>
    </Box>
  );
}

export default function AccountSharing() {
  const { data: sharesData, isLoading: loadingShares, refetch: refetchShares } = useSharedAccounts();
  const { revokeShare, isLoading: revoking } = useRevokeShare({
    onSuccess: () => {
      toastService.success('Access revoked successfully');
    },
    onError: (err) => {
      toastService.error(err.body?.message || 'Failed to revoke access');
    },
  });
  const { updatePermissions, isLoading: updatingPermissions } = useUpdateSharePermissions({
    onSuccess: () => {
      toastService.success('Permissions updated successfully');
    },
    onError: (err) => {
      toastService.error(err.body?.message || 'Failed to update permissions');
    },
  });
  const { deleteShare } = useDeleteShare({
    onError: (err) => {
      toastService.error(err.body?.message || 'Failed to delete share');
    },
  });

  const [clearDialogOpen, setClearDialogOpen] = useState<'active' | 'inactive' | 'all' | null>(null);
  const [isRevoking, setIsRevoking] = useState(false);

  const sharedByMe = sharesData?.data?.sharedByMe || [];
  const sharedWithMe = sharesData?.data?.sharedWithMe || [];

  const handleShareCreated = () => {
    // Trigger a refetch of shares to ensure the newly created share with tempPassword is loaded
    refetchShares();
  };

  // Get active shares (not revoked/expired)
  const activeShares = sharedByMe.filter(share => {
    const isNotRevoked = share.status !== 'revoked';
    const isNotExpired = new Date(share.expiresAt).getTime() >= new Date().getTime();
    return isNotRevoked && isNotExpired;
  });

  // Get inactive shares (revoked or expired)
  const inactiveShares = sharedByMe.filter(share => {
    const isRevoked = share.status === 'revoked';
    const isExpired = new Date(share.expiresAt).getTime() < new Date().getTime();
    return isRevoked || isExpired;
  });

  const handleClearShares = async (type: 'active' | 'inactive' | 'all') => {
    setClearDialogOpen(null);
    setIsRevoking(true);

    try {
      let sharesToDelete = sharedByMe;
      if (type === 'active') {
        sharesToDelete = activeShares;
      } else if (type === 'inactive') {
        sharesToDelete = inactiveShares;
      }

      // Delete selected shares one by one
      let deletedCount = 0;
      for (const share of sharesToDelete) {
        try {
          // Call deleteShare which will revoke active shares and delete the record
          await deleteShare(share.id);
          deletedCount++;
          // Add a small delay to prevent too rapid requests
          await new Promise(resolve => setTimeout(resolve, 200));
        } catch (error) {
          console.error(`Failed to delete share ${share.id}:`, error);
          // Continue with next share even if one fails
        }
      }
      if (deletedCount > 0) {
        toastService.success(`${deletedCount} share(s) cleared successfully`);
      }
    } finally {
      setIsRevoking(false);
    }
  };

  const handleUpdatePermissions = async (shareId: number, permissions: SharePermissions) => {
    await updatePermissions({ shareId, permissions });
  };

  return (
    <div>
      <PermissionRequestsPanel />

      <ShareAccountForm onShareCreated={handleShareCreated} />

      <SectionSubtitle>Accounts I've Shared</SectionSubtitle>
      {loadingShares ? (
        <SkeletonContainer>
          <SkeletonCard>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5, flex: 1 }}>
              <Skeleton variant="text" width="40%" height={20} />
              <Skeleton variant="text" width="60%" height={16} />
            </Box>
            <Skeleton variant="rounded" width={70} height={24} />
          </SkeletonCard>
          <SkeletonCard>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5, flex: 1 }}>
              <Skeleton variant="text" width="35%" height={20} />
              <Skeleton variant="text" width="55%" height={16} />
            </Box>
            <Skeleton variant="rounded" width={70} height={24} />
          </SkeletonCard>
        </SkeletonContainer>
      ) : activeShares.length === 0 && inactiveShares.length === 0 ? (
        <EmptyState>You haven't shared your account with anyone yet.</EmptyState>
      ) : (
        <>
          {sharedByMe.length > 0 && (
            <SectionHeader>
              <div />
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                {activeShares.length > 0 && (
                  <ClearAllButton
                    startIcon={<DeleteOutlineIcon />}
                    onClick={() => setClearDialogOpen('active')}
                    disabled={isRevoking}
                    size="small"
                  >
                    Clear Shared
                  </ClearAllButton>
                )}
                {inactiveShares.length > 0 && (
                  <ClearAllButton
                    startIcon={<DeleteOutlineIcon />}
                    onClick={() => setClearDialogOpen('inactive')}
                    disabled={isRevoking}
                    size="small"
                  >
                    Clear Unshared
                  </ClearAllButton>
                )}
                {sharedByMe.length > 0 && (
                  <ClearAllButton
                    startIcon={<DeleteOutlineIcon />}
                    onClick={() => setClearDialogOpen('all')}
                    disabled={isRevoking}
                    size="small"
                  >
                    Clear All
                  </ClearAllButton>
                )}
              </div>
            </SectionHeader>
          )}
          {activeShares.length > 0 && (
            <>
              <h5 style={{ fontSize: '0.85rem', color: '#999', marginTop: '1rem', marginBottom: '0.5rem' }}>Active Shares</h5>
              <ShareList>
                {activeShares.map((share) => (
                  <ShareCardItem
                    key={share.id}
                    share={share}
                    isOwner={true}
                    onRevoke={revokeShare}
                    onUpdatePermissions={handleUpdatePermissions}
                    isRevoking={revoking}
                    isUpdating={updatingPermissions}
                    tempPassword={share.tempPassword}
                  />
                ))}
              </ShareList>
            </>
          )}
          {inactiveShares.length > 0 && (
            <>
              <h5 style={{ fontSize: '0.85rem', color: '#999', marginTop: '1rem', marginBottom: '0.5rem' }}>Unshared (Expired/Revoked)</h5>
              <ShareList>
                {inactiveShares.map((share) => (
                  <ShareCardItem
                    key={share.id}
                    share={share}
                    isOwner={true}
                    onRevoke={revokeShare}
                    onUpdatePermissions={handleUpdatePermissions}
                    isRevoking={revoking}
                    isUpdating={updatingPermissions}
                  />
                ))}
              </ShareList>
            </>
          )}
        </>
      )}

      <SectionDivider />

      <SectionSubtitle>Accounts Shared With Me</SectionSubtitle>
      {loadingShares ? (
        <SkeletonContainer>
          <SkeletonCard>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5, flex: 1 }}>
              <Skeleton variant="text" width="45%" height={20} />
              <Skeleton variant="text" width="50%" height={16} />
            </Box>
            <Skeleton variant="rounded" width={70} height={24} />
          </SkeletonCard>
        </SkeletonContainer>
      ) : sharedWithMe.length === 0 ? (
        <EmptyState>No one has shared their account with you yet.</EmptyState>
      ) : (
        <ShareList>
          {sharedWithMe.map((share) => (
            <ShareCardItem
              key={share.id}
              share={share}
              isOwner={false}
            />
          ))}
        </ShareList>
      )}

      {/* Clear Shares Confirmation Dialog */}
      <Dialog
        open={clearDialogOpen !== null}
        onClose={() => setClearDialogOpen(null)}
      >
        <DialogTitle>
          {clearDialogOpen === 'active' && 'Clear Shared Accounts?'}
          {clearDialogOpen === 'inactive' && 'Clear Unshared Accounts?'}
          {clearDialogOpen === 'all' && 'Clear All Accounts?'}
        </DialogTitle>
        <DialogContent>
          {clearDialogOpen === 'active' && `Are you sure you want to revoke access for ${activeShares.length} active shared account(s)? Users will be immediately logged out.`}
          {clearDialogOpen === 'inactive' && `Are you sure you want to remove ${inactiveShares.length} expired or revoked account(s)?`}
          {clearDialogOpen === 'all' && `Are you sure you want to revoke/remove all ${sharedByMe.length} account(s)? This action cannot be undone.`}
        </DialogContent>
        <DialogActions>
          <ClearAllButton
            onClick={() => setClearDialogOpen(null)}
            disabled={isRevoking}
          >
            Cancel
          </ClearAllButton>
          <ClearAllButton
            onClick={() => clearDialogOpen && handleClearShares(clearDialogOpen)}
            disabled={isRevoking}
            sx={{ color: '#ef5350' }}
          >
            {isRevoking ? <CircularProgress size={16} sx={{ mr: 0.5 }} /> : null}
            Confirm
          </ClearAllButton>
        </DialogActions>
      </Dialog>
    </div>
  );
}
