import { useState, useMemo } from "react";
import { Box, Collapse } from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import TableViewIcon from "@mui/icons-material/TableView";

import {
  ApisContent,
  EndpointsList,
  EndpointGroup,
  EndpointGroupHeader,
  EndpointGroupTitle,
  EndpointItem,
  MethodBadge,
  EndpointPath,
} from "./ApisPage/ApisPage.styles";
import TryItPanel from "./ApisPage/TryItPanel";
import { usePermissions, AccessRestricted } from "../../components";
import type { ApiEndpoint, ColumnInfo, ColumnType } from "./ApisPage/ApisPage.types";
import { getCrudEndpoints } from "./ApisPage/ApisPage.types";
import { useSchemaObjects, useTableDetails } from "../../api/entities/schema";
import { useDashboard } from "./DashboardLayout";
import type { ColumnDto } from "../../api/models/SchemaDto";

// Map database column types to filter-friendly types
const mapColumnType = (dbType: string): ColumnType => {
  const type = dbType.toLowerCase();

  if (type.includes("bool") || type === "bit" || type === "tinyint(1)") {
    return "boolean";
  }
  if (type.includes("date") && type.includes("time")) {
    return "datetime";
  }
  if (type.includes("date") || type.includes("timestamp")) {
    return "date";
  }
  if (type.includes("time")) {
    return "datetime";
  }
  if (
    type.includes("int") ||
    type.includes("decimal") ||
    type.includes("numeric") ||
    type.includes("float") ||
    type.includes("double") ||
    type.includes("real") ||
    type.includes("money") ||
    type.includes("serial")
  ) {
    return "number";
  }
  if (type.includes("enum")) {
    return "enum";
  }
  return "string";
};

const columnsToFilterInfo = (columns: ColumnDto[]): ColumnInfo[] => {
  return columns.map((col) => ({
    name: col.name,
    type: mapColumnType(col.type),
    isPrimaryKey: col.isPrimaryKey,
    isForeignKey: col.isForeignKey,
    isAutoIncrement:
      col.extra?.toLowerCase().includes("auto_increment") ||
      col.defaultValue?.toLowerCase().includes("nextval"),
  }));
};

interface TableGroup {
  tableName: string;
  endpoints: ApiEndpoint[];
  expanded: boolean;
}

export default function ApisAutoGenerated() {
  const { connectedDatabase } = useDashboard();
  const { canTryAutoApis } = usePermissions();
  const [selectedEndpoint, setSelectedEndpoint] = useState<ApiEndpoint | null>(null);
  const [selectedTable, setSelectedTable] = useState<string | null>(null);
  const [expandedTables, setExpandedTables] = useState<Set<string>>(new Set());

  const { data: schemaData, isLoading } = useSchemaObjects(connectedDatabase?.id);
  const tables = useMemo(
    () => schemaData?.objects?.filter((o) => o.type === "table").map((o) => o.name) || [],
    [schemaData]
  );

  const { data: tableDetails } = useTableDetails(
    connectedDatabase?.id,
    selectedTable ?? undefined
  );

  const columnInfo = useMemo<ColumnInfo[]>(() => {
    if (!tableDetails?.table?.columns) return [];
    return columnsToFilterInfo(tableDetails.table.columns);
  }, [tableDetails]);

  const tableGroups: TableGroup[] = useMemo(() => {
    if (!connectedDatabase) return [];
    return tables.map((tableName) => ({
      tableName,
      endpoints: getCrudEndpoints(connectedDatabase.id, tableName),
      expanded: expandedTables.has(tableName),
    }));
  }, [connectedDatabase, tables, expandedTables]);

  const toggleTableExpanded = (tableName: string) => {
    setExpandedTables((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(tableName)) {
        newSet.delete(tableName);
      } else {
        newSet.add(tableName);
      }
      return newSet;
    });
  };

  const handleSelectEndpoint = (endpoint: ApiEndpoint, tableName: string) => {
    if (!canTryAutoApis) return;
    setSelectedEndpoint(endpoint);
    setSelectedTable(tableName);
  };

  if (!connectedDatabase) return null;

  // Show permission warning if not allowed
  if (!canTryAutoApis) {
    return (
      <ApisContent>
        <Box sx={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <AccessRestricted
            message="Auto-generated APIs Restricted"
            description="You don't have permission to try auto-generated APIs. Please contact the account owner to request access."
            permission="tryAutoGeneratedApis"
          />
        </Box>
      </ApisContent>
    );
  }

  return (
    <ApisContent>
      <EndpointsList>
        {isLoading ? (
          <Box sx={{ p: 2, textAlign: "center", color: "text.secondary" }}>
            Loading tables...
          </Box>
        ) : tables.length === 0 ? (
          <Box sx={{ p: 2, textAlign: "center", color: "text.secondary" }}>
            No tables found in the database.
          </Box>
        ) : (
          tableGroups.map((group) => (
            <EndpointGroup key={group.tableName}>
              <EndpointGroupHeader onClick={() => toggleTableExpanded(group.tableName)}>
                <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                  <TableViewIcon fontSize="small" sx={{ opacity: 0.6 }} />
                  <EndpointGroupTitle>{group.tableName}</EndpointGroupTitle>
                </Box>
                <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                  <Box sx={{ fontSize: "0.75rem", color: "text.secondary" }}>
                    {group.endpoints.length} endpoints
                  </Box>
                  {group.expanded ? (
                    <ExpandLessIcon fontSize="small" />
                  ) : (
                    <ExpandMoreIcon fontSize="small" />
                  )}
                </Box>
              </EndpointGroupHeader>
              <Collapse in={group.expanded}>
                {group.endpoints.map((endpoint) => (
                  <EndpointItem
                    key={endpoint.id}
                    selected={selectedEndpoint?.id === endpoint.id}
                    onClick={() => handleSelectEndpoint(endpoint, group.tableName)}
                  >
                    <MethodBadge method={endpoint.method} label={endpoint.method} />
                    <Box sx={{ flex: 1, minWidth: 0 }}>
                      <Box sx={{ fontSize: "0.8rem", fontWeight: 500, mb: 0.25 }}>
                        {endpoint.summary}
                      </Box>
                      <EndpointPath>
                        {endpoint.path.replace(
                          `/databases/${connectedDatabase.id}/api/`,
                          "/"
                        )}
                      </EndpointPath>
                    </Box>
                  </EndpointItem>
                ))}
              </Collapse>
            </EndpointGroup>
          ))
        )}
      </EndpointsList>

      <TryItPanel endpoint={selectedEndpoint} columns={columnInfo} />
    </ApisContent>
  );
}
