// src/modules/auth/auth.types.ts

import type { ApiResponseDto } from '../../utils/errors';

export interface SignupDto {
  email: string;
  password: string;
  fullName?: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface UserDto {
  id: string;
  email: string;
  fullName?: string;
}

export interface TokenResponseDto {
  token: string;
}

export interface ForgotPasswordDto {
  email: string;
}

export interface VerifyResetCodeDto {
  email: string;
  code: string;
}

export interface ResetPasswordDto {
  email: string;
  code: string;
  newPassword: string;
}

export interface ChangePasswordDto {
  currentPassword: string;
  newPassword: string;
}

export interface ChangeEmailDto {
  newEmail: string;
  password: string;
}

export interface Setup2FADto {
  password: string;
}

export interface Verify2FADto {
  code: string;
}

export interface Disable2FADto {
  password: string;
  code: string;
}

export interface Login2FADto {
  email: string;
  code: string;
  tempToken: string;
}

export interface DeactivateAccountDto {
  password: string;
}

export interface DeleteAccountDto {
  password: string;
  confirmation: string; // must be "DELETE"
}

export interface TwoFactorRequiredDto {
  requires2FA: true;
  tempToken: string;
  email: string;
}

export interface VerifyCodeResultDto {
  valid: boolean;
}

export interface Setup2FAResultDto {
  qrCode: string;
  secret: string;
}

export interface Verify2FAResultDto {
  backupCodes: string[];
}

export interface TwoFactorStatusDto {
  enabled: boolean;
}

// Account Sharing types
export interface SharePermissions {
  // Database operations
  createDatabase: boolean;
  connectDatabase: boolean;
  // Schema operations
  createTable: boolean;
  addColumn: boolean;
  editColumn: boolean;
  deleteColumn: boolean;
  deleteTable: boolean;
  // Data operations
  viewTableData: boolean;
  addRecord: boolean;
  editRecord: boolean;
  deleteRecord: boolean;
  // Query operations
  runQuery: boolean;
  // API operations
  createApiInQueryBuilder: boolean;
  tryAutoGeneratedApis: boolean;
  tryOpenApi: boolean;
  // Settings is always blocked for shared users
}

export const DEFAULT_SHARE_PERMISSIONS: SharePermissions = {
  createDatabase: false,
  connectDatabase: false,
  createTable: false,
  addColumn: false,
  editColumn: false,
  deleteColumn: false,
  deleteTable: false,
  viewTableData: true,
  addRecord: false,
  editRecord: false,
  deleteRecord: false,
  runQuery: false,
  createApiInQueryBuilder: false,
  tryAutoGeneratedApis: false,
  tryOpenApi: false,
};

export interface ShareAccountDto {
  email: string;
  expiresInDays?: number;
  permissions?: Partial<SharePermissions>;
}

export interface AcceptShareDto {
  shareId: number;
}

export interface RevokeShareDto {
  shareId: number;
}

export interface UpdateSharePermissionsDto {
  shareId: number;
  permissions: SharePermissions;
}

export interface SharedLoginDto {
  ownerEmail: string;
  tempPassword: string;
}

export interface SharedAccountDto {
  id: number;
  ownerUserId: number;
  ownerEmail: string;
  ownerFullName: string | null;
  sharedWithEmail: string;
  sharedWithUserId: number | null;
  status: 'pending' | 'accepted' | 'revoked';
  permissions: SharePermissions;
  tempPassword?: string; // Only returned when creating a share
  expiresAt: Date;
  acceptedAt: Date | null;
  revokedAt: Date | null;
  createdAt: Date;
}

export interface NotificationDto {
  id: number;
  userId: number;
  type: 'account_shared' | 'share_accepted' | 'share_revoked' | 'permissions_updated' | 'permission_request' | 'request_approved' | 'request_rejected' | 'general';
  title: string;
  message: string;
  metadata: Record<string, unknown> | null;
  readAt: Date | null;
  createdAt: Date;
}

// Permission Request types
export interface PermissionRequestDto {
  id: number;
  shareId: number;
  requestedBy: number;
  requestedByEmail: string;
  requestedByName: string | null;
  ownerUserId: number;
  permission: keyof SharePermissions;
  status: 'pending' | 'approved' | 'rejected';
  message: string | null;
  responseMessage: string | null;
  createdAt: Date;
  respondedAt: Date | null;
}

export interface CreatePermissionRequestDto {
  permission: keyof SharePermissions;
  message?: string;
}

export interface RespondPermissionRequestDto {
  requestId: number;
  action: 'approve' | 'reject';
  message?: string;
}

export interface PermissionRequestsListDto {
  requests: PermissionRequestDto[];
}

export interface DbPermissionRequestDto {
  id: number;
  share_id: number;
  requested_by: number;
  owner_user_id: number;
  permission: string;
  status: 'pending' | 'approved' | 'rejected';
  message: string | null;
  response_message: string | null;
  created_at: Date;
  responded_at: Date | null;
  updated_at: Date;
}

export interface ShareAccountResultDto {
  share: SharedAccountDto;
  message: string;
}

export interface SharedAccountsListDto {
  sharedByMe: SharedAccountDto[];
  sharedWithMe: SharedAccountDto[];
}

export interface NotificationsListDto {
  notifications: NotificationDto[];
  unreadCount: number;
}

// Database row types for account sharing
export interface DbSharedAccountDto {
  id: number;
  owner_user_id: number;
  shared_with_email: string;
  shared_with_user_id: number | null;
  temp_password_hash: string;
  temp_password: string | null;
  status: 'pending' | 'accepted' | 'revoked';
  permissions: SharePermissions;
  expires_at: Date;
  accepted_at: Date | null;
  revoked_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface DbNotificationDto {
  id: number;
  user_id: number;
  type: 'account_shared' | 'share_accepted' | 'share_revoked' | 'general';
  title: string;
  message: string;
  metadata: string | null;
  read_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface ChangeEmailResultDto {
  token: string;
  message: string;
}

export interface MessageResponseDto {
  message: string;
}

// Database row types
export interface DbUserDto {
  id: string;
  email: string;
  password_hash: string;
  full_name: string | null;
  two_factor_secret: string | null;
  two_factor_enabled: boolean;
  deactivated_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface DbPasswordResetTokenDto {
  id: string;
  user_id: string;
  token: string;
  expires_at: Date;
  used_at: Date | null;
  created_at: Date;
}

export interface DbBackupCodeDto {
  id: string;
  user_id: string;
  code_hash: string;
  used_at: Date | null;
  created_at: Date;
}

export type LoginResponseDto = ApiResponseDto<TokenResponseDto>;

export type SignupResponseDto = ApiResponseDto<TokenResponseDto>;

export type ForgotPasswordResponseDto = ApiResponseDto<MessageResponseDto>;

export type VerifyResetCodeResponseDto = ApiResponseDto<VerifyCodeResultDto>;

export type ResetPasswordResponseDto = ApiResponseDto<MessageResponseDto>;

export type ChangePasswordResponseDto = ApiResponseDto<MessageResponseDto>;

export type ChangeEmailResponseDto = ApiResponseDto<ChangeEmailResultDto>;

export type Setup2FAResponseDto = ApiResponseDto<Setup2FAResultDto>;

export type Verify2FAResponseDto = ApiResponseDto<Verify2FAResultDto>;

export type Disable2FAResponseDto = ApiResponseDto<MessageResponseDto>;

export type TwoFactorStatusResponseDto = ApiResponseDto<TwoFactorStatusDto>;

export type Login2FAResponseDto = ApiResponseDto<TokenResponseDto>;

export type TwoFactorRequiredResponseDto = ApiResponseDto<TwoFactorRequiredDto>;

export type DeactivateAccountResponseDto = ApiResponseDto<MessageResponseDto>;

export type DeleteAccountResponseDto = ApiResponseDto<MessageResponseDto>;

// Account sharing response types
export type ShareAccountResponseDto = ApiResponseDto<ShareAccountResultDto>;

export type SharedAccountsResponseDto = ApiResponseDto<SharedAccountsListDto>;

export type AcceptShareResponseDto = ApiResponseDto<MessageResponseDto>;

export type RevokeShareResponseDto = ApiResponseDto<MessageResponseDto>;

export type SharedLoginResponseDto = ApiResponseDto<TokenResponseDto>;

export type NotificationsResponseDto = ApiResponseDto<NotificationsListDto>;

export type MarkNotificationReadResponseDto = ApiResponseDto<MessageResponseDto>;
// Permission request response types
export type PermissionRequestsResponseDto = ApiResponseDto<PermissionRequestsListDto>;

export type CreatePermissionRequestResponseDto = ApiResponseDto<{ request: PermissionRequestDto }>;

export type RespondPermissionRequestResponseDto = ApiResponseDto<MessageResponseDto>;