import { cloneElement, useState, useEffect, type CSSProperties } from 'react';
import { Tooltip } from '@mui/material';
import { hasPermission, onPermissionsChange } from '../../api/httpClient';
import type { SharePermissions } from '../../api/models/SharedAccountDto';

interface PermissionGateProps {
    permission: keyof SharePermissions;
    children: React.ReactElement<{ disabled?: boolean; onClick?: () => void; style?: CSSProperties }>;
    tooltipText?: string;
}

/**
 * Wraps a component and disables it if user lacks permission.
 * Shows a tooltip explaining the restriction.
 */
export function PermissionGate({
    permission,
    children,
    tooltipText = "You're not permitted to do this action"
}: PermissionGateProps) {
    const allowed = hasPermission(permission);

    if (allowed) {
        return children;
    }

    // Clone the child element with disabled prop
    const disabledChild = cloneElement(children, {
        disabled: true,
        onClick: undefined,
        style: {
            ...(children.props.style || {}),
            pointerEvents: 'auto' as const,
            opacity: 0.5,
            cursor: 'not-allowed',
        },
    });

    return (
        <Tooltip title={tooltipText} arrow>
            <span style={{ display: 'inline-block' }}>
                {disabledChild}
            </span>
        </Tooltip>
    );
}

/**
 * Hook to check multiple permissions at once
 * Re-renders when permissions are updated via WebSocket
 */
export function usePermissions() {
    const [, setTrigger] = useState(0);

    useEffect(() => {
        // Subscribe to permission changes and auto-cleanup on unmount
        return onPermissionsChange(() => setTrigger(t => t + 1));
    }, []);

    return {
        hasPermission,
        can: (permission: keyof SharePermissions) => hasPermission(permission),
        canCreateDatabase: hasPermission('createDatabase'),
        canConnectDatabase: hasPermission('connectDatabase'),
        canCreateTable: hasPermission('createTable'),
        canAddColumn: hasPermission('addColumn'),
        canEditColumn: hasPermission('editColumn'),
        canDeleteColumn: hasPermission('deleteColumn'),
        canDeleteTable: hasPermission('deleteTable'),
        canViewTableData: hasPermission('viewTableData'),
        canEditTableData: hasPermission('editTableData'),
        canRunQuery: hasPermission('runQuery'),
        canCreateApi: hasPermission('createApiInQueryBuilder'),
        canTryAutoApis: hasPermission('tryAutoGeneratedApis'),
        canTryOpenApi: hasPermission('tryOpenApi'),
    };
}

export default PermissionGate;
