import { cloneElement, type CSSProperties } from 'react';
import { Tooltip } from '@mui/material';
import { usePermissionsContext } from '../../context/PermissionsContext';
import type { SharePermissions } from '../../api/models/SharedAccountDto';

interface PermissionGateProps {
    permission: keyof SharePermissions;
    children: React.ReactElement<{ disabled?: boolean; onClick?: () => void; style?: CSSProperties }>;
    tooltipText?: string;
}

/**
 * Wraps a component and disables it if user lacks permission.
 * Shows a tooltip explaining the restriction.
 * Updates live when permissions change via WebSocket.
 */
export function PermissionGate({
    permission,
    children,
    tooltipText = "You're not permitted to do this action"
}: PermissionGateProps) {
    const { hasPermission } = usePermissionsContext();
    const allowed = hasPermission(permission);

    if (allowed) {
        return children;
    }

    // Clone the child element with disabled prop
    const disabledChild = cloneElement(children, {
        disabled: true,
        onClick: undefined,
        style: {
            ...(children.props.style || {}),
            pointerEvents: 'auto' as const,
            opacity: 0.5,
            cursor: 'not-allowed',
        },
    });

    return (
        <Tooltip title={tooltipText} arrow>
            <span style={{ display: 'inline-block' }}>
                {disabledChild}
            </span>
        </Tooltip>
    );
}

/**
 * Hook to check multiple permissions at once
 * Updates live when permissions change via WebSocket
 */
export function usePermissions() {
    const { hasPermission, permissions, isSharedAccess, isLoading } = usePermissionsContext();

    return {
        permissions,
        isSharedAccess,
        isLoading,
        hasPermission,
        can: (permission: keyof SharePermissions) => hasPermission(permission),
        canCreateDatabase: hasPermission('createDatabase'),
        canConnectDatabase: hasPermission('connectDatabase'),
        canCreateTable: hasPermission('createTable'),
        canAddColumn: hasPermission('addColumn'),
        canEditColumn: hasPermission('editColumn'),
        canDeleteColumn: hasPermission('deleteColumn'),
        canDeleteTable: hasPermission('deleteTable'),
        canViewTableData: hasPermission('viewTableData'),
        canAddRecord: hasPermission('addRecord'),
        canEditRecord: hasPermission('editRecord'),
        canDeleteRecord: hasPermission('deleteRecord'),
        canRunQuery: hasPermission('runQuery'),
        canCreateApi: hasPermission('createApiInQueryBuilder'),
        canTryAutoApis: hasPermission('tryAutoGeneratedApis'),
        canTryOpenApi: hasPermission('tryOpenApi'),
    };
}

export default PermissionGate;
