import { cloneElement, type CSSProperties } from 'react';
import { Tooltip } from '@mui/material';
import { usePermissionsContext } from '../../context/PermissionsContext';
import type { SharePermissions } from '../../api/models/SharedAccountDto';
import { isDemoModeActive } from '../../context/TourContext';

interface PermissionGateProps {
    permission: keyof SharePermissions;
    children: React.ReactElement<{ disabled?: boolean; onClick?: () => void; style?: CSSProperties }>;
    tooltipText?: string;
}

/**
 * Wraps a component and disables it if user lacks permission.
 * Shows a tooltip explaining the restriction.
 * Updates live when permissions change via WebSocket.
 */
export function PermissionGate({
    permission,
    children,
    tooltipText = "You're not permitted to do this action"
}: PermissionGateProps) {
    const { hasPermission } = usePermissionsContext();
    const isDemo = isDemoModeActive();
    
    // In demo mode, allow all actions (mutations will return mock data)
    const allowed = isDemo || hasPermission(permission);

    if (allowed) {
        return children;
    }

    // Clone the child element with disabled prop
    const disabledChild = cloneElement(children, {
        disabled: true,
        onClick: undefined,
        style: {
            ...(children.props.style || {}),
            pointerEvents: 'auto' as const,
            opacity: 0.5,
            cursor: 'not-allowed',
        },
    });

    return (
        <Tooltip title={tooltipText} arrow>
            <span style={{ display: 'inline-block' }}>
                {disabledChild}
            </span>
        </Tooltip>
    );
}

/**
 * Hook to check multiple permissions at once
 * Updates live when permissions change via WebSocket
 * In demo mode, all permissions are granted (mutations return mock data)
 */
export function usePermissions() {
    const { hasPermission, permissions, isSharedAccess, isLoading } = usePermissionsContext();
    const isDemo = isDemoModeActive();

    // In demo mode, grant all permissions (the hooks/httpClient handle mock responses)
    const checkPermission = (permission: keyof SharePermissions) => isDemo || hasPermission(permission);

    return {
        permissions,
        isSharedAccess,
        isLoading,
        hasPermission: checkPermission,
        can: (permission: keyof SharePermissions) => checkPermission(permission),
        canCreateDatabase: checkPermission('createDatabase'),
        canConnectDatabase: checkPermission('connectDatabase'),
        canCreateTable: checkPermission('createTable'),
        canAddColumn: checkPermission('addColumn'),
        canEditColumn: checkPermission('editColumn'),
        canDeleteColumn: checkPermission('deleteColumn'),
        canDeleteTable: checkPermission('deleteTable'),
        canViewTableData: checkPermission('viewTableData'),
        canAddRecord: checkPermission('addRecord'),
        canEditRecord: checkPermission('editRecord'),
        canDeleteRecord: checkPermission('deleteRecord'),
        canRunQuery: checkPermission('runQuery'),
        canCreateApi: checkPermission('createApiInQueryBuilder'),
        canTryAutoApis: checkPermission('tryAutoGeneratedApis'),
        canTryOpenApi: checkPermission('tryOpenApi'),
    };
}

export default PermissionGate;
