/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export interface SharePermissions {
  // Database operations
  createDatabase: boolean;
  connectDatabase: boolean;
  // Schema operations
  createTable: boolean;
  addColumn: boolean;
  editColumn: boolean;
  deleteColumn: boolean;
  deleteTable: boolean;
  // Data operations
  viewTableData: boolean;
  editTableData: boolean;
  // Query operations
  runQuery: boolean;
  // API operations
  createApiInQueryBuilder: boolean;
  tryAutoGeneratedApis: boolean;
  tryOpenApi: boolean;
}

export const DEFAULT_SHARE_PERMISSIONS: SharePermissions = {
  createDatabase: false,
  connectDatabase: false,
  createTable: false,
  addColumn: false,
  editColumn: false,
  deleteColumn: false,
  deleteTable: false,
  viewTableData: true,
  editTableData: false,
  runQuery: false,
  createApiInQueryBuilder: false,
  tryAutoGeneratedApis: false,
  tryOpenApi: false,
};

export interface SharedAccountDto {
  id: number;
  ownerUserId: number;
  ownerEmail: string;
  ownerFullName: string | null;
  sharedWithEmail: string;
  sharedWithUserId: number | null;
  status: 'pending' | 'accepted' | 'revoked';
  permissions: SharePermissions;
  tempPassword?: string;
  expiresAt: string;
  acceptedAt: string | null;
  revokedAt: string | null;
  createdAt: string;
}
// Permission request types
export interface PermissionRequestDto {
  id: number;
  shareId: number;
  requestedBy: number;
  requestedByEmail: string;
  requestedByName: string | null;
  ownerUserId: number;
  permission: keyof SharePermissions;
  status: 'pending' | 'approved' | 'rejected';
  message: string | null;
  responseMessage: string | null;
  createdAt: string;
  respondedAt: string | null;
}

export interface CreatePermissionRequestDto {
  permission: keyof SharePermissions;
  message?: string;
}

export interface RespondPermissionRequestDto {
  requestId: number;
  action: 'approve' | 'reject';
  message?: string;
}

export interface PermissionRequestsListDto {
  requests: PermissionRequestDto[];
}

export interface PermissionRequestsResponseDto {
  status: string;
  message: string;
  data: PermissionRequestsListDto;
}

export interface CreatePermissionRequestResponseDto {
  status: string;
  message: string;
  data: { request: PermissionRequestDto };
}