// Styles for AutoGenerated tab - self-contained styles

import { Box, Chip, styled } from "@mui/material";
import { getDashboardColors } from "../../../styles/theme";

export const ApisContent = styled(Box)({
  display: 'flex',
  flex: 1,
  gap: '1rem',
  minHeight: 0,
  overflow: 'hidden',
  width: '100%',
});

export const EndpointsList = styled(Box)(({ theme }) => {
  const colors = getDashboardColors(theme.palette.mode === 'dark');
  return {
    width: '400px',
    minWidth: '400px',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    overflowY: 'auto',
    paddingRight: '0.5rem',
    borderRight: `1px solid ${colors.border}`,
  };
});

export const EndpointGroup = styled(Box)(({ theme }) => {
  const colors = getDashboardColors(theme.palette.mode === 'dark');
  return {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: '0.5rem',
    border: `1px solid ${colors.border}`,
    overflow: 'hidden',
  };
});

export const EndpointGroupHeader = styled(Box)(({ theme }) => {
  const colors = getDashboardColors(theme.palette.mode === 'dark');
  return {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0.75rem 1rem',
    backgroundColor: colors.backgroundTertiary,
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: colors.backgroundHover,
    },
  };
});

export const EndpointGroupTitle = styled('span')(({ theme }) => {
  const colors = getDashboardColors(theme.palette.mode === 'dark');
  return {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: colors.text,
  };
});

export const EndpointItem = styled(Box, {
  shouldForwardProp: (prop) => prop !== 'selected',
})<{ selected?: boolean }>(({ theme, selected }) => {
  const colors = getDashboardColors(theme.palette.mode === 'dark');
  return {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.75rem 1rem',
    cursor: 'pointer',
    borderBottom: `1px solid ${colors.border}`,
    backgroundColor: selected ? colors.backgroundHover : 'transparent',
    '&:last-child': {
      borderBottom: 'none',
    },
    '&:hover': {
      backgroundColor: colors.backgroundHover,
    },
  };
});

export const MethodBadge = styled(Chip, {
  shouldForwardProp: (prop) => prop !== 'method',
})<{ method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' }>(({ method }) => {
  const methodColors: Record<string, { bg: string; color: string }> = {
    GET: { bg: '#61affe20', color: '#61affe' },
    POST: { bg: '#49cc9020', color: '#49cc90' },
    PUT: { bg: '#fca13020', color: '#fca130' },
    PATCH: { bg: '#50e3c220', color: '#50e3c2' },
    DELETE: { bg: '#f93e3e20', color: '#f93e3e' },
  };
  const colors = methodColors[method] || methodColors.GET;
  return {
    height: '24px',
    minWidth: '60px',
    fontSize: '0.7rem',
    fontWeight: 700,
    backgroundColor: colors.bg,
    color: colors.color,
    borderRadius: '4px',
    '& .MuiChip-label': {
      padding: '0 8px',
    },
  };
});

export const EndpointPath = styled('span')(({ theme }) => {
  const colors = getDashboardColors(theme.palette.mode === 'dark');
  return {
    fontSize: '0.8rem',
    fontFamily: 'monospace',
    color: colors.textSecondary,
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  };
});
