// src/modules/databases/crud/crud.routes.ts

import { Router } from 'express';
import { authMiddleware, requirePermissions } from '../../../middleware/auth';
import {
  listRecordsHandler,
  getRecordHandler,
  createRecordHandler,
  updateRecordHandler,
  patchRecordHandler,
  deleteRecordHandler,
  getTableRelationsHandler,
  getRelatedRecordsHandler,
} from './crud.controller';

const router = Router();

// All routes require authentication
router.use(authMiddleware);

/**
 * Dynamic CRUD API Routes
 * 
 * Base URL: /databases/:id/api/:table
 * 
 * Permission Requirements for Shared Access Users:
 * - GET operations: require tryAutoGeneratedApis permission
 * - POST/PUT/PATCH/DELETE operations: require editTableData permission
 * 
 * Supported operations:
 * - GET    /databases/:id/api/:table                    - List records (with pagination, filtering, sorting, search)
 * - GET    /databases/:id/api/:table/relations          - Get table relations
 * - GET    /databases/:id/api/:table/:recordId          - Get single record by ID
 * - GET    /databases/:id/api/:table/:recordId/:related - Get related records (nested route)
 * - POST   /databases/:id/api/:table                    - Create new record
 * - PUT    /databases/:id/api/:table                    - Full update records by filter
 * - PATCH  /databases/:id/api/:table                    - Partial update records by filter
 * - DELETE /databases/:id/api/:table                    - Delete records by filter
 * 
 * Query Parameters for list endpoints:
 * - page: Page number (default: 1)
 * - limit: Records per page (default: 20, max: 100)
 * - offset: Skip N records (alternative to page)
 * - sortBy: Column to sort by
 * - sortOrder: 'asc' or 'desc' (default: 'asc')
 * - search: Text search across searchable columns
 * - searchFields: Columns to search in (comma-separated or array)
 * - [column]: Filter by column value (e.g., ?status=active&category=1)
 * 
 * Examples:
 * - GET /databases/1/api/users?page=1&limit=10&sortBy=created_at&sortOrder=desc
 * - GET /databases/1/api/products?search=laptop&category=electronics
 * - GET /databases/1/api/orders?status=pending&user_id=5
 * - GET /databases/1/api/users/5/orders - Get all orders for user 5
 */

// Get table relations - must be before :recordId to avoid conflict
// Requires tryAutoGeneratedApis AND viewTableData permissions for shared users
router.get('/:id/api/:table/relations', requirePermissions('tryAutoGeneratedApis', 'viewTableData'), getTableRelationsHandler as any);

// List records with pagination, filtering, sorting, search
// Requires tryAutoGeneratedApis AND viewTableData permissions for shared users
router.get('/:id/api/:table', requirePermissions('tryAutoGeneratedApis', 'viewTableData'), listRecordsHandler as any);

// Get single record by ID
// Requires tryAutoGeneratedApis AND viewTableData permissions for shared users
router.get('/:id/api/:table/:recordId', requirePermissions('tryAutoGeneratedApis', 'viewTableData'), getRecordHandler as any);

// Get related records (nested route)
// Requires tryAutoGeneratedApis AND viewTableData permissions for shared users
router.get('/:id/api/:table/:recordId/:relatedTable', requirePermissions('tryAutoGeneratedApis', 'viewTableData'), getRelatedRecordsHandler as any);

// Create new record
// Requires tryAutoGeneratedApis AND addColumn permissions for shared users
router.post('/:id/api/:table', requirePermissions('tryAutoGeneratedApis', 'addColumn'), createRecordHandler as any);

// Full update records by filter
// Requires tryAutoGeneratedApis AND editTableData permissions for shared users
router.put('/:id/api/:table', requirePermissions('tryAutoGeneratedApis', 'editTableData'), updateRecordHandler as any);

// Partial update records by filter
// Requires tryAutoGeneratedApis AND editTableData permissions for shared users
router.patch('/:id/api/:table', requirePermissions('tryAutoGeneratedApis', 'editTableData'), patchRecordHandler as any);

// Delete records by filters (no recordId required)
// Requires tryAutoGeneratedApis AND deleteColumn permissions for shared users
router.delete('/:id/api/:table', requirePermissions('tryAutoGeneratedApis', 'deleteColumn'), deleteRecordHandler as any);

export default router;
