import React, { useMemo, useState, lazy, Suspense } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createAppTheme } from "./styles/theme";
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from "@mui/material";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  Navigate,
} from "react-router-dom";
import {
  ErrorBoundary,
  ToastProvider,
  ProtectedRoute,
  ProtectedNotFoundRoute,
  DemoBanner,
} from "./components";
import { PermissionsProvider } from "./context/PermissionsContext";
import { TourProvider } from "./context/TourContext";
import { ROUTES } from "./constants";

// Lazy load pages for better initial load performance
const Home = lazy(() => import("./pages/Home/Home"));
const SignIn = lazy(() => import("./pages/SignIn/SignIn"));
const SignUp = lazy(() => import("./pages/SignUp/SignUp"));
const SharedLogin = lazy(() => import("./pages/SharedLogin/SharedLogin"));
const ChangePassword = lazy(() => import("./pages/ChangePassword/ChangePassword"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword/ForgotPassword"));
const OAuthCallback = lazy(() => import("./pages/OAuthCallback/OAuthCallback"));
const Settings = lazy(() => import("./pages/Settings/Settings"));
const Feedback = lazy(() => import("./pages/Feedback/Feedback"));
const Limits = lazy(() => import("./pages/Limits/Limits"));

// Workspace layout (shared between Dashboard and APIs)
const WorkspaceLayout = lazy(() => import("./layout/WorkspaceLayout/WorkspaceLayout").then(m => ({ default: m.default })));
const DashboardLayout = lazy(() => import("./layout/DashboardLayout/DashboardLayout").then(m => ({ default: m.default })));
const ApisLayout = lazy(() => import("./layout/ApisLayout/ApisLayout").then(m => ({ default: m.default })));

// Dashboard pages
const DashboardOverview = lazy(() => import("./pages/DashboardPage/Overview"));
const DashboardSchema = lazy(() => import("./pages/DashboardPage/Schema"));
const DashboardQuery = lazy(() => import("./pages/DashboardPage/Query"));
const DashboardERDiagram = lazy(() => import("./pages/DashboardPage/ERDiagram"));

// APIs pages
const ApisBuildQuery = lazy(() => import("./pages/ApisPage/BuildQuery"));
const ApisAutoGenerated = lazy(() => import("./pages/ApisPage/AutoGenerated"));
const ApisOpenApi = lazy(() => import("./pages/ApisPage/OpenApi"));

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      refetchOnWindowFocus: false,
    },
    mutations: {
      retry: 0,
    },
  },
});

type AppContextType = {
  darkMode: boolean;
  setDarkMode: (mode: boolean) => void;
};

export const AppContext = React.createContext<AppContextType>({
  darkMode: true,
  setDarkMode: () => { },
});

const App: React.FC = () => {
  // Initialize darkMode from localStorage, default to true (dark mode)
  const [darkMode, setDarkModeState] = useState<boolean>(() => {
    const saved = localStorage.getItem('prism-theme');
    return saved !== null ? saved === 'dark' : true;
  });

  // Wrapper to persist theme changes to localStorage
  const setDarkMode = (mode: boolean) => {
    setDarkModeState(mode);
    localStorage.setItem('prism-theme', mode ? 'dark' : 'light');
  };

  const appTheme = useMemo(() => createAppTheme(darkMode), [darkMode]);

  return (
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <ThemeProvider theme={appTheme}>
          <AppContext.Provider value={{ darkMode, setDarkMode }}>
            <CssBaseline />
            <PermissionsProvider>
              <Router>
                <ToastProvider>
                  <TourProvider>
                    <DemoBanner />
                    <Suspense fallback={null}>
                      <Routes>
                      {/* Home page */}
                      <Route path={ROUTES.HOME} element={<Home />} />

                      {/* Auth pages */}
                      <Route path={ROUTES.SIGN_IN} element={<SignIn />} />
                      <Route path={ROUTES.SHARED_LOGIN} element={<SharedLogin />} />
                      <Route path={ROUTES.SIGN_UP} element={<SignUp />} />
                      <Route path={ROUTES.OAUTH_CALLBACK} element={<OAuthCallback />} />
                      <Route path={ROUTES.CHANGE_PASSWORD} element={<ChangePassword />} />
                      <Route path={ROUTES.FORGOT_PASSWORD} element={<ForgotPassword />} />

                      {/* Dashboard */}
                      <Route path={ROUTES.DASHBOARD.ROOT} element={
                        <ProtectedRoute>
                          <WorkspaceLayout />
                        </ProtectedRoute>
                      }>
                        <Route element={<DashboardLayout />}>
                          <Route index element={<Navigate to="overview" replace />} />
                          <Route path="overview" element={<DashboardOverview />} />
                          <Route path="schema" element={<DashboardSchema />} />
                          <Route path="query" element={<DashboardQuery />} />
                          <Route path="er-diagram" element={<DashboardERDiagram />} />
                        </Route>
                      </Route>

                      {/* APIs */}
                      <Route path={ROUTES.APIS.ROOT} element={
                        <ProtectedRoute>
                          <WorkspaceLayout />
                        </ProtectedRoute>
                      }>
                        <Route element={<ApisLayout />}>
                          <Route index element={<Navigate to="build" replace />} />
                          <Route path="build" element={<ApisBuildQuery />} />
                          <Route path="auto" element={<ApisAutoGenerated />} />
                          <Route path="openapi" element={<ApisOpenApi />} />
                        </Route>
                      </Route>

                      {/* Settings */}
                      <Route path={ROUTES.SETTINGS} element={
                        <ProtectedRoute blockSharedAccess>
                          <Settings />
                        </ProtectedRoute>
                      } />

                      {/* Feedback */}
                      <Route path={ROUTES.FEEDBACK} element={
                        <ProtectedRoute>
                          <Feedback />
                        </ProtectedRoute>
                      } />

                      {/* Limits */}
                      <Route path={ROUTES.LIMITS} element={
                        <ProtectedRoute>
                          <Limits />
                        </ProtectedRoute>
                      } />

                      <Route path="*" element={<ProtectedNotFoundRoute />} />
                      </Routes>
                    </Suspense>
                  </TourProvider>
                </ToastProvider>
              </Router>
            </PermissionsProvider>
          </AppContext.Provider>
        </ThemeProvider>
      </QueryClientProvider>
    </ErrorBoundary>
  );
};

export default App;
