import React, { useMemo, useState } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createAppTheme } from "./styles/theme";
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from "@mui/material";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  Navigate,
} from "react-router-dom";
import Home from "./pages/Home/Home";
import SignIn from "./pages/SignIn/SignIn";
import SignUp from "./pages/SignUp/SignUp";
import SharedLogin from "./pages/SharedLogin/SharedLogin";
import ChangePassword from "./pages/ChangePassword/ChangePassword";
import ForgotPassword from "./pages/ForgotPassword/ForgotPassword";
import DashboardLayout from "./pages/Dashboard/DashboardLayout";
import { DashboardOverview, DashboardSchema, DashboardQuery, ApisLayout, ApisBuildQuery, ApisAutoGenerated, ApisOpenApi } from "./pages/Dashboard";
import Settings from "./pages/Settings/Settings";
import { ErrorBoundary, ToastProvider, ProtectedRoute } from "./components";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      refetchOnWindowFocus: false,
    },
    mutations: {
      retry: 0,
    },
  },
});

type AppContextType = {
  darkMode: boolean;
  setDarkMode: (mode: boolean) => void;
};

export const AppContext = React.createContext<AppContextType>({
  darkMode: true,
  setDarkMode: () => {},
});

const App: React.FC = () => {
  // Initialize darkMode from localStorage, default to true (dark mode)
  const [darkMode, setDarkModeState] = useState<boolean>(() => {
    const saved = localStorage.getItem('prism-theme');
    return saved !== null ? saved === 'dark' : true;
  });

  // Wrapper to persist theme changes to localStorage
  const setDarkMode = (mode: boolean) => {
    setDarkModeState(mode);
    localStorage.setItem('prism-theme', mode ? 'dark' : 'light');
  };

  const appTheme = useMemo(() => createAppTheme(darkMode), [darkMode]);

  return (
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <ThemeProvider theme={appTheme}>
          <AppContext.Provider value={{ darkMode, setDarkMode }}>
            <CssBaseline />
            <ToastProvider>
              <Router>
                <Routes>
                  <Route path="/" element={<Home />} />
                  <Route path="/signin" element={<SignIn />} />
                  <Route path="/shared-login" element={<SharedLogin />} />
                  <Route path="/signup" element={<SignUp />} />
                  <Route path="/change-password" element={<ChangePassword />} />
                  <Route path="/forgot-password" element={<ForgotPassword />} />
                  <Route path="/dashboard" element={<DashboardLayout />}>
                    <Route index element={<Navigate to="overview" replace />} />
                    <Route path="overview" element={<DashboardOverview />} />
                    <Route path="apis" element={<ApisLayout />}>
                      <Route index element={<Navigate to="build" replace />} />
                      <Route path="build" element={<ApisBuildQuery />} />
                      <Route path="auto" element={<ApisAutoGenerated />} />
                      <Route path="openapi" element={<ApisOpenApi />} />
                    </Route>
                    <Route path="schema" element={<DashboardSchema />} />
                    <Route path="query" element={<DashboardQuery />} />
                  </Route>
                  <Route path="/settings" element={
                    <ProtectedRoute blockSharedAccess>
                      <Settings />
                    </ProtectedRoute>
                  } />
                </Routes>
              </Router>
            </ToastProvider>
          </AppContext.Provider>
        </ThemeProvider>
      </QueryClientProvider>
    </ErrorBoundary>
  );
};

export default App;
